---
apiVersion: v1
kind: Service
metadata:
  name: front-end
  namespace: dev
  labels:
    name: front-end
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8079
    # nodePort: 30001
  selector:
    name: front-end