---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-db
  namespace: dev
  labels:
    name: orders-db
spec:
  replicas: 1
  selector:
    matchLabels:
      name: orders-db
  template:
    metadata:
      labels:
        name: orders-db
    spec:
      containers:
      - name: orders-db
        image: {{if .Values.global.registry}}{{ .Values.global.registry }}/{{end}}{{ .Values.ordersdb.image.repo }}:{{ .Values.ordersdb.image.tag }}
        ports:
        - name: mongo
          containerPort: 27017
        resources:
{{ toYaml .Values.ordersdb.resources | indent 10 }}
        securityContext:
          capabilities:
            drop:
              - all
            add:
              - CHOWN
              - SETGID
              - SETUID
          readOnlyRootFilesystem: true
          runAsUser: 999  # Set to MongoDB's default UID
          runAsGroup: 999 # Set to MongoDB's default GID
        volumeMounts:
        # - mountPath: /tmp
        #   name: tmp-volume
        - mountPath: /data/db  # Mounting the PVC here for MongoDB storage
          name: orders-db-storage  # This matches the PVC
      volumes:
        # - name: tmp-volume
        #   emptyDir:
        #     medium: Memory
        - name: orders-db-storage
          persistentVolumeClaim:
            claimName: ordersdb-pvc  # Refers to the PVC
      #   volumeMounts:
      #   - mountPath: /tmp
      #     name: tmp-volume
      # volumes:
      #   - name: tmp-volume
      #     emptyDir:
      #       medium: Memory
