---
apiVersion: v1
kind: Service
metadata:
  name: user
  namespace: dev
  labels:
    name: user
spec:
  ports:
    # the port that this service should serve on
  - port: 80
    targetPort: {{ .Values.user.containerPort }}
  selector:
    name: user
